# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

  target 'KHJCamera' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'SVProgressHUD'
  pod 'SDWebImage'
  pod 'FFToast'
  pod 'CocoaAsyncSocket', '~> 7.4.1'

  # Pods for KHJCamera
end
